"""Build app/deck_site.py: app/deck.py with the DATA block (between # DATA-START and # DATA-END)
replaced by an inlined JSON literal, so the deck can be exported as a static WebAssembly site.

    python3 scripts/build_deck_site.py
    marimo export html-wasm app/deck_site.py -o site --mode run
"""
import json, os, re, runpy, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
src = open("app/deck.py").read()
block = src[src.index("    # DATA-START"):src.index("    # DATA-END") + len("    # DATA-END")]
ns = {"json": json, "os": os, "__file__": os.path.abspath("app/deck.py")}
exec("import json, os\n" + "\n".join(ln[4:] for ln in block.splitlines()), ns)       # run the loader to get DATA
data = ns["DATA"]
lit = "    DATA = json.loads(" + json.dumps(json.dumps(data)) + ")"
out = src.replace(block, lit).replace('"""Helix demo deck:', '"""GENERATED by scripts/build_deck_site.py; edit app/deck.py instead.\n\nHelix demo deck:')
open("app/deck_site.py", "w").write(out)
print(f"app/deck_site.py: {len(out)//1024} KB, {len(data['naive']['leads'])} naive leads, {len(data['prod']['leads'])} product leads, {len(data['rules'])} rulebooks")
